// Run against the isolated local acceptance server; never against production.
const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.TEST_URL||'http://127.0.0.1:8765';
if(!/^http:\/\/(127\.0\.0\.1|localhost)(:\d+)?\/?$/.test(url))throw Error('Use an isolated localhost server.');
if(!process.env.TEST_UNLOCK_CODE)throw Error('Set the temporary local TEST_UNLOCK_CODE.');
const results=[],check=(name,value)=>{assert.ok(value,name);results.push(name);};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1100,height:844}}),p=await context.newPage(),errors=[];
 const failedAssets=[],externalRequests=[],dialogs=[];
 p.setDefaultTimeout(5000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>{dialogs.push(d.message());return d.accept();});p.on('response',r=>{if(r.status()>=400)failedAssets.push(r.url());});p.on('request',r=>{if(!r.url().startsWith(url)&&!r.url().startsWith('data:'))externalRequests.push(r.url());});
 await p.goto(url);await p.locator('#llgUnlockInput').fill(process.env.TEST_UNLOCK_CODE);await p.locator('#llgUnlockBtn').click();await p.locator('#llgLockScreen').waitFor({state:'hidden'});
 check('No startup errors',errors.length===0);check('No assistant banner',await p.getByText('Ask about your plant',{exact:true}).count()===0);
 check('Clean isolated database',await p.evaluate(()=>['customPlants','personalJournal','wish','plants','prop','care','expenses'].every(k=>db[k].length===0)));
 for(const view of ['dashboard','plants','care','propagation','wishlist','budget','guide','journal','help']){await p.evaluate(v=>go(v),view);check('Empty view '+view,await p.locator('#'+view).isVisible());}
 await p.getByRole('button',{name:'⚙️ More',exact:true}).click();await p.getByRole('button',{name:'📖 Plant Care Guide',exact:true}).click();
 await p.getByRole('button',{name:'101 Plant Parent Questions',exact:true}).click();check('101 FAQ cards',await p.locator('.faqCard').count()===101);
 for(const query of ['bugs in dirt','bugs in soil','tiny bugs','soil bugs']){await p.locator('#faqSearch').fill(query);check('FAQ keyword '+query,(await p.locator('#faqResults').innerText()).includes('crawling IN my soil'));}
 await p.locator('#faqSearch').fill('');await p.locator('#faqCategory').selectOption({label:'Propagation'});check('FAQ category filter',await p.locator('.faqCard').count()===10);await p.locator('.faqCard summary').first().click();check('FAQ answer opens',await p.locator('.faqCard[open]').count()===1);
 await p.locator('.faqCard summary').first().click();check('FAQ answer collapses',await p.locator('.faqCard[open]').count()===0);await p.locator('#faqCategory').selectOption('');
 for(const category of await p.evaluate(()=>[...new Set(PlantFAQ.map(e=>e.category))])){await p.locator('#faqCategory').selectOption(category);check('FAQ category '+category,await p.locator('.faqCard').count()>0);}
 await p.locator('#faqCategory').selectOption('');for(const [query,id]of [['hydrophobic',6],['bright indirect light',61],['insects in dirt',21]]){await p.locator('#faqSearch').fill(query);check('FAQ answer/title/alias search '+query,(await p.locator('#faqResults').innerText()).includes(id+'. '));}await p.locator('#faqSearch').fill('zxqnonexistent');check('FAQ empty results',await p.locator('.faqCard').count()===0);await p.locator('#faqSearch').fill('');check('FAQ clear restores 101',await p.locator('.faqCard').count()===101);
 await p.getByRole('button',{name:'Plant Library',exact:true}).click();check('Curated guide 101',await p.locator('.guidePlantCard').count()===101);
 for(let i=0;i<101;i++){await p.locator('.guideOpen').nth(i).click();check('Curated detail '+i,(await p.locator('#sheet').innerText()).length>50);await p.getByRole('button',{name:'Close',exact:true}).click();}
 await p.getByRole('button',{name:'+ Add Your Own Plant',exact:true}).click();check('All 13 custom fields',await p.locator('#customPlantForm [id^=content_]').count()===13);check('101 visual avatars',await p.locator('.avatarChoice').count()===101);
 const fullPlant={name:"QA Gardener's Plant",botanical:'Scindapsus pictus',careGroup:'Pothos & Scindapsus',growthHabit:'Climbing / trailing',tags:'QA Tag; Easy Care',petNote:'Toxic',tip:'A silvery vine; rotate gently and inspect new growth.',light:'Bright indirect light',soilCheck:'Check below the surface; allow the upper mix to dry.',humidity:'Average home humidity',soil:'Airy bark, potting mix and perlite',fertilizer:'Diluted feed during active growth',interval:'8'};for(const [key,value]of Object.entries(fullPlant))await p.locator('#content_'+key).fill(value);await p.getByRole('button',{name:'Use Golden Pothos avatar',exact:true}).click();await p.getByRole('button',{name:'Save my plant',exact:true}).click();check('All custom fields saved',await p.evaluate(v=>Object.entries(v).every(([k,val])=>String(db.customPlants[0][k])===val),fullPlant));
 check('Custom saved to guide',await p.locator('.guidePlantCard').count()===102);await p.locator('#guideSearch').fill("QA Gardener's");check('Custom guide search',await p.locator('.guidePlantCard').count()===1);
 await p.locator('#guideFilterCG').selectOption('Pothos & Scindapsus');await p.locator('#guideFilterTag').selectOption('QA Tag');await p.locator('#guideFilterPet').selectOption('Toxic');check('Custom guide combined filters',await p.locator('.guidePlantCard').count()===1);await p.locator('#guideFilterCG').selectOption('');await p.locator('#guideFilterTag').selectOption('');await p.locator('#guideFilterPet').selectOption('');
 await p.locator('.guideOpen').click();check('Custom detail safe apostrophe',(await p.locator('#sheet').innerText()).includes("QA Gardener's Plant"));
 await p.getByRole('button',{name:'Add to My Plants',exact:true}).click();check('Custom in My Plants type',await p.locator('#f_profile').inputValue()==="QA Gardener's Plant");await p.locator('#f_nickname').fill('QA Collection Plant');await p.getByRole('button',{name:'Save plant',exact:true}).click();check('Added custom tracked plant',await p.evaluate(()=>db.plants.length===1&&!!db.plants[0].guideId));
 const stableId=await p.evaluate(()=>db.customPlants[0].id);check('Custom artwork and shared care lookup',await p.evaluate(()=>plantSticker(db.customPlants[0].name)===plantSticker('Golden Pothos')&&findGuideMatch(db.plants[0].profile).interval===8));
 await p.evaluate(()=>{go('budget');openForm('expense');});await p.locator('#f_category').selectOption('Plants');await p.locator('#f_item').fill('Silvery vine purchase');await p.locator('#f_plant').selectOption({label:'QA Collection Plant'});await p.locator('#f_actual').fill('18.75');await p.locator('#sheet button').filter({hasText:/Save purchase/}).click();check('Custom tracked purchase saved with stable IDs',await p.evaluate(()=>db.expenses.some(e=>e.actual===18.75&&e.plantId===db.plants[0].id&&e.guideId===db.customPlants[0].id)));
 await p.evaluate(()=>go('dashboard'));await p.getByRole('button',{name:'+ Plant',exact:true}).click();check('Custom in Quick Add datalist',(await p.locator('datalist').allTextContents()).join(' ').includes("QA Gardener's Plant"));await p.getByRole('button',{name:'Close',exact:true}).click();
 await p.getByRole('button',{name:'+ Care',exact:true}).click();await p.locator('#quickPlantId').selectOption({label:'QA Collection Plant'});await p.getByLabel('Watered',{exact:true}).check();await p.getByRole('button',{name:'Save care',exact:true}).click();check('Custom Quick Care record',await p.evaluate(()=>db.care.length===1));
 await p.getByRole('button',{name:'+ Health Concern',exact:true}).click();await p.locator('#quickPlantId').selectOption({label:'QA Collection Plant'});await p.locator('#quickNote').fill('A yellow leaf');await p.getByRole('button',{name:'Save for later',exact:true}).click();check('Custom Health Concern record',await p.evaluate(()=>db.care.length===2));
 await p.evaluate(()=>openCareEntry(db.plants[0].id,'health'));check('Full Health Concern opens without chat links',await p.locator('#f_symptoms').isVisible()&&await p.getByText('Ask about your plant',{exact:true}).count()===0);await p.locator('#f_pestFlag').selectOption('Yes');await p.locator('#f_pest').selectOption('Spider Mites');check('Existing Health Log pest guidance',(await p.locator('#knownPestTreatment').innerText()).includes('Rinse'));await p.getByRole('button',{name:'Close',exact:true}).click();
 await p.evaluate(()=>{go('guide');setGuideSub('library');});await p.locator('#guideSearch').fill("QA Gardener's");await p.getByRole('button',{name:"Add QA Gardener's Plant to wishlist",exact:true}).click();check('Custom Wishlist stable relation',await p.evaluate(()=>!!db.wish[0].guideId));
 await p.evaluate(()=>openForm('wish'));check('Custom in Wishlist picker',(await p.locator('#wishlistPlantChoice').innerText()).includes("QA Gardener's Plant"));await p.getByRole('button',{name:'Close',exact:true}).click();
 await p.evaluate(()=>{go('propagation');openForm('prop');});check('Custom tracked plant in Propagation',(await p.locator('#f_parent').innerText()).includes('QA Collection Plant'));await p.locator('#f_parent').selectOption({label:'QA Collection Plant'});await p.getByRole('button',{name:'Save propagation',exact:true}).click();check('Propagation stable parent relationship',await p.evaluate(()=>!!db.prop[0].parentPlantId&&!!db.prop[0].guideId));
 await p.getByRole('button',{name:'⚙️ More',exact:true}).click();await p.getByRole('button',{name:'📓 My Garden Log',exact:true}).click();check('Existing automatic log still contains activity',(await p.locator('#journalPages').innerText()).includes('QA Collection Plant'));await p.getByRole('button',{name:'Journal',exact:true}).click();
 await p.getByRole('button',{name:'+ Write an entry',exact:true}).click();await p.locator('#content_body').fill('I want to rearrange the balcony.');await p.getByRole('button',{name:'Save journal entry',exact:true}).click();check('General Journal entry',await p.locator('.personalJournalCard').count()===1);
 await p.getByRole('button',{name:'+ Write an entry',exact:true}).click();await p.locator('#content_title').fill('New leaf');await p.locator('#content_body').fill('A milestone!');await p.locator('#journalAssociation').selectOption({label:'QA Collection Plant'});await p.getByRole('button',{name:'Save journal entry',exact:true}).click();check('Plant linked Journal entry',await p.evaluate(()=>!!db.personalJournal[1].plantId));
 await p.getByRole('button',{name:'+ Write an entry',exact:true}).click();await p.locator('#content_body').fill('Custom guide note');await p.locator('#journalAssociation').selectOption({label:"QA Gardener's Plant — My Entry"});await p.getByRole('button',{name:'Save journal entry',exact:true}).click();check('Custom guide Journal entry',await p.evaluate(()=>!!db.personalJournal[2].guideId));
 const created=await p.evaluate(()=>db.personalJournal[0].createdAt);await p.getByRole('button',{name:'Edit entry',exact:true}).last().click();await p.locator('#content_body').fill('Revised balcony plans.');await p.locator('#journalEntryAt').fill('2026-09-01T10:30');await p.getByRole('button',{name:'Save journal entry',exact:true}).click();check('Journal edit preserves timestamp',await p.evaluate(t=>db.personalJournal[0].createdAt===t,created));check('Editable Journal entry date',await p.evaluate(()=>db.personalJournal[0].entryAt.startsWith('2026-09-01')));
 await p.reload();check('Custom and Journal persist',await p.evaluate(()=>LIB.length===102&&db.personalJournal.length===3&&!!db.plants[0].guideId));
 await p.evaluate(()=>{go('guide');setGuideSub('library');});await p.locator('#guideSearch').fill("QA Gardener's");await p.locator('.guideOpen').click();await p.getByRole('button',{name:'Edit my entry',exact:true}).click();await p.locator('#content_name').fill('QA Renamed Plant');await p.getByRole('button',{name:'Use Monstera deliciosa avatar',exact:true}).click();await p.getByRole('button',{name:'Save my plant',exact:true}).click();check('Rename updates linked profile and wishlist',await p.evaluate(()=>db.plants[0].profile==='QA Renamed Plant'&&db.wish[0].name==='QA Renamed Plant'));check('Avatar change persists',await p.evaluate(()=>db.customPlants[0].avatar==='Monstera deliciosa'));
 check('Rename retains UUID and all relationships',await p.evaluate(id=>db.customPlants.length===1&&db.customPlants[0].id===id&&db.expenses[0].guideId===id&&db.prop[0].guideId===id&&db.care.every(e=>e.plantId===db.plants[0].id)&&db.personalJournal[2].guideId===id,stableId));check('New avatar shared by historical and tracked lookup',await p.evaluate(()=>plantSticker(db.plants[0].profile)===plantSticker('Monstera deliciosa')));
 await p.locator('#guideSearch').fill('QA Renamed');await p.locator('.guideOpen').click();await p.getByRole('button',{name:'Delete my entry',exact:true}).click();check('Safe delete preserves referenced data',await p.evaluate(()=>LIB.length===101&&db.customPlants[0].deleted&&db.plants.length===1&&db.personalJournal.length===3&&db.prop.length===1));
 check('Referenced deletion warning shown',dialogs.some(s=>s.includes('saved records')&&s.includes('history')));check('Deletion preserves purchase and care history',await p.evaluate(()=>db.expenses[0].actual===18.75&&db.care.length===2&&db.customPlants[0].avatar==='Monstera deliciosa'));
 await p.reload();check('Historical custom resolution survives reload',await p.evaluate(()=>findGuideMatch(db.plants[0].guideId)?.name==='QA Renamed Plant'));
 await p.evaluate(()=>go('journal'));await p.getByRole('button',{name:'Journal',exact:true}).click();await p.getByRole('button',{name:'Delete entry',exact:true}).first().click();check('Journal delete',await p.locator('.personalJournalCard').count()===2);
 await p.getByRole('button',{name:'+ Write an entry',exact:true}).click();await p.locator('#content_body').fill('Unsaved draft must survive a storage failure.');await p.evaluate(()=>{window.qaOriginalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('Storage full in test');};});await p.getByRole('button',{name:'Save journal entry',exact:true}).click();check('Journal storage failure keeps the text and does not save',await p.locator('#content_body').inputValue()==='Unsaved draft must survive a storage failure.'&&await p.evaluate(()=>db.personalJournal.length===2));await p.evaluate(()=>{Storage.prototype.setItem=window.qaOriginalSet;delete window.qaOriginalSet;});await p.getByRole('button',{name:'Cancel',exact:true}).click();
 await p.evaluate(()=>{db.budget=500;db.settings.categoryBudgets={Plants:100,'Pots & Planters':100};db.expenses.push({id:900,item:'QA pot',category:'Pots & Planters',purchaseStatus:'planned',plannedAmount:30,actual:0,date:localISODate()});save();go('budget');});
 const invoke=kind=>p.evaluate(k=>{if(k==='total')void setBudget();else if(k==='paid')void markExpensePurchased(900);else void transferBudgetMoney('Plants','Pots & Planters',0);},kind);
 for(const kind of ['total','paid','move']){const before=await p.evaluate(()=>JSON.stringify(db));await invoke(kind);await p.locator('#panelValueInput').fill('999');await p.getByRole('button',{name:'Close',exact:true}).click();check('Budget cancel '+kind,await p.evaluate(()=>JSON.stringify(db))===before);}
 for(const [kind,amount]of [['total','550.75'],['paid','24.65'],['move','12.35']]){await invoke(kind);await p.locator('#panelValueInput').fill(amount);await p.locator('#panelValueForm button').click();check('Budget decimal '+kind,await p.evaluate(k=>k==='total'?db.budget===550.75:k==='paid'?db.expenses.find(e=>e.id===900).actual===24.65:db.settings.categoryBudgets.Plants===87.65&&db.settings.categoryBudgets['Pots & Planters']===112.35,kind));}
 await p.evaluate(()=>{go('guide');setGuideSub('library');});await p.locator('#guideSearch').fill('Golden Pothos');for(let i=0;i<12;i++){await p.locator('.guidePlantCard').filter({hasText:'Golden Pothos'}).locator('.guideWishlistHeart').click();check('Repeated Wishlist toggle '+i,await p.evaluate(expected=>db.wish.filter(w=>w.name==='Golden Pothos').length===expected,i%2===0?1:0));}await p.locator('.guidePlantCard').filter({hasText:'Golden Pothos'}).locator('.guideWishlistHeart').click();await p.evaluate(()=>markPurchased(db.wish.find(w=>w.name==='Golden Pothos').id));await p.locator('#purchasePriceInput').fill('22.45');await p.getByRole('button',{name:'Save price',exact:true}).click();check('Wishlist purchase updates expense and tracked relationship',await p.evaluate(()=>{const w=db.wish.find(w=>w.name==='Golden Pothos');return w.actual===22.45&&db.expenses.find(e=>e.wishId===w.id).actual===22.45&&db.plants.some(p=>p.fromWishlistId===w.id);}));
 await p.evaluate(()=>openPurchasePriceEditor(db.wish.find(w=>w.name==='Golden Pothos').id));await p.locator('#purchasePriceInput').fill('not money');await p.getByRole('button',{name:'Save price',exact:true}).click();check('Wishlist price rejects malformed currency',await p.evaluate(()=>db.wish.find(w=>w.name==='Golden Pothos').actual===22.45));await p.getByRole('button',{name:'Close',exact:true}).click();
 await p.evaluate(()=>openBudgetSetup());await p.locator('#budgetOverallInput').fill('600.50');await p.locator('.catBudgetAmount[data-cat="Plants"]').fill('200.25');await p.locator('#budgetPeriodType').selectOption('custom');await p.locator('#budgetPeriodStart').fill('2026-09-01');await p.locator('#budgetPeriodEnd').fill('2026-09-30');await p.evaluate(()=>saveBudgetSetup());check('Budget setup decimals and timeframe',await p.evaluate(()=>db.budget===600.50&&db.settings.categoryBudgets.Plants===200.25&&db.settings.budgetPeriodEnd==='2026-09-30'));check('Budget spent total matches the three purchases',(await p.locator('#bSpent').innerText()).includes('65.85'));
 await p.evaluate(()=>openBudgetSetup());await p.locator('#budgetOverallInput').fill('-10');await p.evaluate(()=>saveBudgetSetup());check('Budget setup rejects negative total',await p.evaluate(()=>db.budget===600.50));await p.getByRole('button',{name:'Close',exact:true}).click();
 await p.evaluate(()=>openBudgetSetup());await p.locator('.catBudgetAmount[data-cat="Plants"]').fill('-20');await p.evaluate(()=>saveBudgetSetup());check('Budget setup rejects negative category',await p.evaluate(()=>db.settings.categoryBudgets.Plants===200.25));await p.getByRole('button',{name:'Close',exact:true}).click();
 await p.evaluate(()=>{go('guide');setGuideSub('library');});await p.getByRole('button',{name:'+ Add Your Own Plant',exact:true}).click();await p.locator('#content_name').fill('QA unused plant');await p.getByRole('button',{name:'Save my plant',exact:true}).dblclick();check('Double custom save creates one record',await p.evaluate(()=>db.customPlants.filter(c=>c.name==='QA unused plant').length===1));await p.evaluate(()=>{closeSheet();go('guide');setGuideSub('library');});await p.locator('#guideSearch').fill('QA unused plant');await p.locator('.guideOpen').click();await p.getByRole('button',{name:'Delete my entry',exact:true}).click();check('Unreferenced plant fully deleted',await p.evaluate(()=>!db.customPlants.some(c=>c.name==='QA unused plant')));
 await p.evaluate(()=>openCustomPlant());await p.locator('#content_name').fill('QA Renamed Plant');await p.getByRole('button',{name:'Save my plant',exact:true}).click();check('Historical name is reserved',(await p.locator('#contentError').innerText()).includes('already'));
 await p.getByRole('button',{name:'Cancel',exact:true}).click();
 for(let i=0;i<10;i++){await p.evaluate(()=>openCustomPlant());await p.getByRole('button',{name:'Cancel',exact:true}).click();await p.evaluate(()=>go('journal'));await p.getByRole('button',{name:'Journal',exact:true}).click();await p.getByRole('button',{name:'+ Write an entry',exact:true}).click();await p.locator('#content_body').fill('Entry '+i+' — '+"A gardener's notes & observations. ".repeat(80));await p.getByRole('button',{name:'Save journal entry',exact:true}).dblclick();}check('Rapid journal double submissions do not duplicate',await p.evaluate(()=>db.personalJournal.length===12));
 const snapshot=await p.evaluate(()=>JSON.stringify(db));for(let i=0;i<3;i++){await p.reload();check('Repeated persistence '+i,await p.evaluate(()=>JSON.stringify(db))===snapshot);}const reopened=await context.newPage();await reopened.goto(url);check('Close/reopen equivalent shares persistent data',await reopened.evaluate(()=>JSON.stringify(db))===snapshot);await reopened.close();
 for(const [sub,fn]of [['caregroups','careGroupDetail'],['pests','pestDetail'],['symptoms','symptomDetail'],['budget','soilDetail']]){await p.evaluate(s=>{go('guide');setGuideSub(s);},sub);const selector='#guide [onclick^="'+fn+'("]';for(let i=0,n=await p.locator(selector).count();i<n;i++){await p.locator(selector).nth(i).click();check(sub+' detail '+i,(await p.locator('#sheet').innerText()).length>30);await p.getByRole('button',{name:'Close',exact:true}).click();}}
 await p.evaluate(()=>openHouseplantSettings());check('Settings panel opens',await p.locator('#overlay.on').count()===1);await p.getByRole('button',{name:'Close',exact:true}).click();
 for(const width of [1100,390,320]){await p.setViewportSize({width,height:844});for(const view of ['dashboard','plants','care','propagation','wishlist','budget','guide','journal','help']){await p.evaluate(v=>go(v),view);check('Visible '+view+' '+width,await p.locator('#'+view).isVisible());check('No overflow '+view+' '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await p.evaluate(()=>{go('guide');setGuideSub('faq');});check('FAQ mobile overflow '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await p.locator('#faqSearch').fill('bugs in dirt');await p.locator('.faqCard summary').first().click();if(process.env.TEST_ARTIFACT_DIR)await p.screenshot({path:process.env.TEST_ARTIFACT_DIR+'/garden-faq-mobile.png'});
 await p.evaluate(()=>openCustomPlant());check('Mobile avatar picker and form have no horizontal overflow',await p.evaluate(()=>document.getElementById('sheet').scrollWidth<=document.getElementById('sheet').clientWidth));if(process.env.TEST_ARTIFACT_DIR)await p.screenshot({path:process.env.TEST_ARTIFACT_DIR+'/garden-custom-mobile.png'});await p.getByRole('button',{name:'Cancel',exact:true}).click();
 await p.evaluate(()=>go('journal'));await p.getByRole('button',{name:'Journal',exact:true}).click();if(process.env.TEST_ARTIFACT_DIR)await p.screenshot({path:process.env.TEST_ARTIFACT_DIR+'/garden-journal-mobile.png'});
 const other=await browser.newContext(),q=await other.newPage();await q.goto(url);check('Other browser has no custom data',await q.evaluate(()=>db.customPlants.length===0&&db.personalJournal.length===0&&LIB.length===101));await q.evaluate(()=>localStorage.setItem('llg_full_app_v58',JSON.stringify({plants:[{id:41,nickname:'Legacy',profile:'Golden Pothos'}],wish:[],expenses:[],care:[],prop:[],garden:[],settings:{},budget:71.25,journal:[{id:42,type:'plants',plant:'Legacy',date:'2026-09-01',time:'10:30',action:'Plant added'}]})));await q.reload();check('Legacy database initializes without losing records or renaming keys',await q.evaluate(()=>db.plants[0].id===41&&db.journal.some(e=>e.id===42)&&db.budget===71.25&&db.customPlants.length===0&&db.personalJournal.length===0&&localStorage.getItem('llg_full_app_v58')!==null));await other.close();
 check('No runtime errors',errors.length===0);check('No missing assets',failedAssets.length===0);check('No external answer generation requests',externalRequests.length===0);console.log(JSON.stringify({passed:results.length,checks:results,errors,failedAssets,externalRequests},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(JSON.stringify({passed:results.length,last:results.at(-1),error:e.stack},null,2));process.exitCode=1;});
